### ISSUE TITLE
dont work correct with rgbw bulbs

### ISSUE THREAD

**Issue by lnx13** [shamasis/homebridge-milight-hub#1]
there is no options to change color/while mode in home application, only in config with "white" parameter

**Comment by lnx13** [comment]
I think we should send {"bulb_mode":"white","color":{"r":255,"g":255,"b":255}} if saturation < 10, and "bulb_mode":"color" with correct color parameter otherwise

**Comment by z-smoker** [comment]
same problem...
the lights are in homekit - but "no answer"

**Comment by fierfr** [comment]
Same problem

**Comment by gregdotcom** [comment]
are there any news about that problem?

**Comment by shamasis** [comment]
People. Sorry I missed the thread. The original issue is around not being able to control white/color mode in Homekit. There seems to be an issue around how Homekit sends this instruction and conflict how the bulbs interpret it. Once it goes into white mode, it does not go back to colour mode.

I will put some time into seeing if I can add mode where, this will work, but the light will momentarily flicker to set to a known state.

**Comment by gregdotcom** [comment]
Hey shamasis, many thanks for your answer :)
Can we help you in any way? 
Let me know if we can test something.

**Comment by shamasis** [comment]
I have found the issue: 

- The bulbs actually have two distinct modes, each retaining their brightness value separately
- The two modes are colour and white
- The bulb needs to be explicitly set to white mode if it was previously set in colour mode and then operated upon (this is what I was not doing)

I am compiling these combinations. I have only RGB+CCT models... hence @MCGregorUK would love your help if you have other bulb variants.

**Comment by shamasis** [comment]
Can anyone try `homebridge-milight-hub@2.0.0-alpha.3` to check if RGBW is working fine? 

@MCGregorUK 

Note: Have a look at README here https://github.com/shamasis/homebridge-milight-hub/tree/feature/platform-support

The config for this release makes the `group` and `type` fields mandatory. Without type, the RGBW failover will not work.

> disclaimer: backup your config and Homebridge before trying this out. It is unlikely to break, but if it does, better to be safe than sorry.

**Comment by gregdotcom** [comment]
> Can anyone try `homebridge-milight-hub@2.0.0-alpha.3` to check if RGBW is working fine?
> 
> @MCGregorUK
> 
> Note: Have a look at README here https://github.com/shamasis/homebridge-milight-hub/tree/feature/platform-support
> 
> The config for this release makes the `group` and `type` fields mandatory. Without type, the RGBW failover will not work.
> 
> > disclaimer: backup your config and Homebridge before trying this out. It is unlikely to break, but if it does, better to be safe than sorry.

Thanks Shamasis!

I tested the @2.0.0-alpha.3 but had to readd the devices that it changes the color to white.
So it works, but now i have a little "glitch" if i set a Color with the colorpicker. Its hard to explain so i made a gif https://imgur.com/138hV5i

Is it also possible to enable a log for your plugin? Is see it in your code that you logging informations but i can't see where it could be enabled.

**Comment by shamasis** [comment]
Pushed `alpha.4`

That is really hard to explain!!! I can see it. It is super odd. I checked on my phone and saw it too. Have not found the solution yet, but I have a hunch that it would be fixed if I deep dive into Homebridge and see if white handling needs any additional information. Plugin documentation of Homebridge is scanty, so I am browsing through as many other matured plugins I can find.

Another problem is that Milight hub returns the color from color state, but homekit expects it whatever the equivalent temperature state it needs. I have tried addressing the problem in alpha.4 (but I am not sure how it will react until we try.) More work is needed from my end to solve the weird colour picker issue.

If you have other white bulbs running off Homebridge through other plugins or directly to homekit, can you show me how they behave? I have Phillips hue white bulb to test (connected directly to homekit via hue bridge) and even that is a bit wonky. 🧐

To see logs, enable Homebridge debug mode. https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#debug-mode

PS: I am also using the free "Eve" app for HomeKit on my iPhone in order to better see stuff. It is a great App if you haven't tried.

**Comment by shamasis** [comment]
Also @MCGregorUK ... thanks for trying it. And I am sorry that you had to re-add the bulbs. Had to make the breaking identification changes to support the `type` storage. Hence bumping it to v2.0

**Comment by shamasis** [comment]
I have pushed `alpha.5` ... it makes the colour picker less finicky, but it seems that it cannot get better than this (at least to the best of my current knowledge)

**Comment by shamasis** [comment]
Published `beta.1` with the changes from `alpha.5`.

This release also adds the ability to auto discover devices added as alias in your Milight Hub. Which means, just adding the following in your config will auto import all bulbs that are added to Milight Hub

```
{
  "name": "Milight Hub",
  "platform": "Milight Hub"
}
```

More on this at https://github.com/shamasis/homebridge-milight-hub/tree/feature/platform-support#2-auto-adding-all-bulbs-addded-directly-in-milight-hub

**Comment by shamasis** [comment]
`beta.3` fixes colour picker issue in temperature mode for Homekit and makes it a bit wonky for Eve app instead. This, IMHO is a livable compromise for now. :-(

beta.3 also adds 10s interval polling to keep any state change caused from outside on the hub to be synced back. Will incorporate UDP when I get it to work (that will remove polling method). :-/
